### ISSUE TITLE
大佬就解答

### ISSUE THREAD

**Issue by ghost** [mox-hub/campus_bus_sys#1]
大佬，你好，请问前端项目是怎么部署的

**Comment by mox-hub** [comment]
你好，本项目的前端部分分为两个板块，其中：

1. campus_bus 是项目的小程序部分，使用的是 uniapp
2. campus_bus_admin是项目的网页管理端，使用了Vue

如果你想跑起来前端项目，需要你有以下准备：

1. 建议使用软件[HBuilderX](https://dcloud.io/hbuilderx.html)，配置uniapp环境，并使用模拟器启动 campus_bus 模块。
2. 可以使用 [Visual Studio Code](https://code.visualstudio.com/)，结合vue相关插件启动 campus_bus_admin 模块。

另外，如果你之前并未部署过前端项目，
在这之前，你首先要配置vue 3的相关环境，包括node.js等。关于这部分网上有很多教程，这里不再赘述。
